schema_version: 1

# TODO: hack to workaround https://github.com/conda-forge/rattler-build-conda-compat/issues/112
context:
  cdt_build_number: 111
  distro: centos7

package:
  name: libdrm-devel-conda-ppc64le
  version: 2.4.97

source:
  - url: https://vault.centos.org/altarch/7.9.2009/os/ppc64le/Packages/libdrm-devel-2.4.97-2.el7.ppc64le.rpm
    sha256: 81529030e4ec8cdd44c9733622d91c4a08bff7b378b3352c89351ff9431bc54f
    target_directory: binary
  # - url: https://vault.centos.org/altarch/7.9.2009/os/Source/SPackages/libdrm-2.4.97-2.el7.src.rpm
  #   target_directory: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: distro != "centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - '*'

requirements:
  build:
    - kernel-headers-conda-ppc64le >=2.6.27 *_${{ cdt_build_number|int + 1000 }}
    - libdrm-conda-ppc64le ==2.4.97 *_${{ cdt_build_number|int + 1000 }}
    - libarchive
  host:
    - kernel-headers-conda-ppc64le >=2.6.27 *_${{ cdt_build_number|int + 1000 }}
    - libdrm-conda-ppc64le ==2.4.97 *_${{ cdt_build_number|int + 1000 }}
    - sysroot_linux-ppc64le 2.17.*
  run:
    - kernel-headers-conda-ppc64le >=2.6.27 *_${{ cdt_build_number|int + 1000 }}
    - libdrm-conda-ppc64le ==2.4.97 *_${{ cdt_build_number|int + 1000 }}
    - sysroot_linux-ppc64le 2.17.*

tests:
  - script:
      - echo "it installs!"

about:
  homepage: http://dri.sourceforge.net
  license: MIT
  summary: (CDT) Direct Rendering Manager development package
  description: |
    Direct Rendering Manager development package

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
