schema_version: 1

# TODO: hack to workaround https://github.com/conda-forge/rattler-build-conda-compat/issues/112
context:
  cdt_build_number: 111
  distro: centos7

package:
  name: libxcomposite-conda-ppc64le
  version: 0.4.4

source:
  - url: https://vault.centos.org/altarch/7.9.2009/os/ppc64le/Packages/libXcomposite-0.4.4-4.1.el7.ppc64le.rpm
    sha256: aade53ea2d9b66196421b4b02843b6ad410ccbda74a5282e1af9806a525e277a
    target_directory: binary
  # - url: https://vault.centos.org/altarch/7.9.2009/os/Source/SPackages/libXcomposite-0.4.4-4.1.el7.src.rpm
  #   target_directory: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: distro != "centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - "*"

requirements:
  build:
    - libarchive
  host:
    - sysroot_linux-ppc64le 2.17.*
  run:
    - sysroot_linux-ppc64le 2.17.*

tests:
  - script:
      - echo "it installs!"

about:
  homepage: http://www.x.org
  license: MIT
  license_file: binary/usr/share/doc/libXcomposite-0.4.4/COPYING
  summary: (CDT) X Composite Extension library
  description: |
        X Composite Extension library

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
