schema_version: 1

# TODO: hack to workaround https://github.com/conda-forge/rattler-build-conda-compat/issues/112
context:
  cdt_build_number: 111
  distro: alma8

package:
  name: kmod-devel-conda-x86_64
  version: 25

source:
  - url: https://repo.almalinux.org/almalinux/8.10/PowerTools/x86_64/os/Packages/kmod-devel-25-20.el8.x86_64.rpm
    sha256: 0c034dc83e4ed123fddaab81984949e54d277f900ada837ccde3c14fc903cf28
    target_directory: binary
  # - url: https://repo.almalinux.org/almalinux/8.10/PowerTools/Source/Packages/kmod-25-20.el8.src.rpm
  #   target_directory: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: distro != "alma8"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - '*'

requirements:
  build:
    - kmod-libs-conda-x86_64 ==25 *_${{ cdt_build_number|int + 1000 }}
    - libarchive
  host:
    - kmod-libs-conda-x86_64 ==25 *_${{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.28.*
  run:
    - kmod-libs-conda-x86_64 ==25 *_${{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.28.*

tests:
  - script:
      - echo "it installs!"

about:
  homepage: http://git.kernel.org/?p=utils/kernel/kmod/kmod.git;a=summary
  license: GPL-2.0-or-later
  license_file: kmod-copying
  summary: (CDT) Header files for kmod development
  description: |
    The kmod-devel package provides header files used for development of
    applications that wish to load or unload Linux kernel modules.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
