schema_version: 1

package:
  name: xcb-util-image-devel-conda-ppc64le
  version: 0.4.0

source:
  - url: https://vault.centos.org/altarch/7.9.2009/os/ppc64le/Packages/xcb-util-image-devel-0.4.0-2.el7.ppc64le.rpm
    sha256: 5d6e1c77e9f73cf2dc302ca87af5340c60be2361f722fa6168c21a8bd45dd59a
    target_directory: binary
    no_hoist: true
  # - url: https://vault.centos.org/altarch/7.9.2009/os/Source/SPackages/xcb-util-image-0.4.0-2.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: "distro != "\centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - "*"

requirements:
  build:
    - xcb-util-image-conda-ppc64le ==0.4.0 *_{{ cdt_build_number|int + 1000 }}
  host:
    - xcb-util-image-conda-ppc64le ==0.4.0 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-ppc64le 2.17.*
  run:
    - xcb-util-image-conda-ppc64le ==0.4.0 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-ppc64le 2.17.*

tests:
  script:
    - "echo "it installs!""

about:
  license: MIT
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: (CDT) Development and header files for xcb-util-image
  description: |
        Development files for xcb-util-image.


  homepage: http://xcb.freedesktop.org

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
