schema_version: 1

package:
  name: xcb-util-wm-devel-conda-x86_64
  version: 0.4.1

source:
  - url: https://vault.centos.org/7.9.2009/os/x86_64/Packages/xcb-util-wm-devel-0.4.1-5.el7.x86_64.rpm
    sha256: 8666865fc1ac715d44389860fe7da624657de669dd8d99f210e3089787fdc954
    target_directory: binary
    no_hoist: true
  # - url: https://vault.centos.org/7.9.2009/os/Source/SPackages/xcb-util-wm-0.4.1-5.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: "distro != "\centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - "*"

requirements:
  build:
    - xcb-util-wm-conda-x86_64 ==0.4.1 *_{{ cdt_build_number|int + 1000 }}
  host:
    - xcb-util-wm-conda-x86_64 ==0.4.1 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.17.*
  run:
    - xcb-util-wm-conda-x86_64 ==0.4.1 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.17.*

tests:
  script:
    - "echo "it installs!""

about:
  license: MIT
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: (CDT) Development and header files for xcb-util-vm
  description: |
        Development files for xcb-util-wm.


  homepage: http://xcb.freedesktop.org

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
