schema_version: 1

package:
  name: glib2-devel-conda-ppc64le
  version: 2.56.1

source:
  - url: https://vault.centos.org/altarch/7.9.2009/os/ppc64le/Packages/glib2-devel-2.56.1-7.el7.ppc64le.rpm
    sha256: 6c878a7a58579b09fa446c538f4190782d71e068e9957f45c5c40548a256ad9d
    target_directory: binary
    no_hoist: true
  # - url: https://vault.centos.org/altarch/7.9.2009/os/Source/SPackages/glib2-2.56.1-7.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: "distro != "\centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - "*"

requirements:
  build:
    - glib2-conda-ppc64le ==2.56.1 *_{{ cdt_build_number|int + 1000 }}
  host:
    - glib2-conda-ppc64le ==2.56.1 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-ppc64le 2.17.*
  run:
    - glib2-conda-ppc64le ==2.56.1 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-ppc64le 2.17.*

tests:
  script:
    - "echo "it installs!""

about:
  license: LGPL-2.0-or-later
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: (CDT) A library of handy utility functions
  description: |
        The glib2-devel package includes the header files for the GLib library.


  homepage: http://www.gtk.org

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
