#!/usr/bin/env sh

# Print all files provided by CDT packages.
#
# Original author: David Banas <capn.freako@gmail.com>
# Original date:   March 23, 2023
#
# Copyright (c) 2023 David Banas; all rights reserved World wide.

# License is hereby granted to all to do anything and everything with this code,
# as long as the above copyright notice and licensing granted herein are
# included and maintained in any distributed copies and/or derivative works.

rm -rf rpms/ 2>/dev/null
mkdir rpms
for url in $(grep 'url:' cdts/*/meta.yaml | cut -f 2- -w | grep '^-' | cut -f 3 -w);
  do curl --output "rpms/${url##*/}" $url;
  done
for rpm in $(ls rpms/);
  do echo "\n${rpm}";
     echo "==========";
     tar tf "rpms/${rpm}" | sort;
  done

