schema_version: 1

package:
  name: kmod-libs-conda-x86_64
  version: 20

source:
  - url: https://vault.centos.org/7.9.2009/os/x86_64/Packages/kmod-libs-20-28.el7.x86_64.rpm
    sha256: e7fd34c97b67902f6a81f9a6e9e38a9e0a1bc60253bac2fd315801b3e2365289
    target_directory: binary
    no_hoist: true
  # - url: https://vault.centos.org/7.9.2009/os/Source/SPackages/kmod-20-28.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: "distro != "\centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - "*"

requirements:
  host:
    - sysroot_linux-64 2.17.*
  run:
    - sysroot_linux-64 2.17.*

tests:
  script:
    - "echo "it installs!""

about:
  license: LGPL-2.0-or-later
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: (CDT) Libraries to handle kernel module loading and unloading
  description: |
        The kmod-libs package provides runtime libraries for any application that
        wishes to load or unload Linux kernel modules from the running system.


  homepage: http://git.kernel.org/?p=utils/kernel/kmod/kmod.git;a=summary

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
