schema_version: 1

# TODO: hack to workaround https://github.com/conda-forge/rattler-build-conda-compat/issues/112
context:
  cdt_build_number: 111
  distro: centos7

package:
  name: libpng-conda-x86_64
  version: 1.5.13

source:
  - url: https://vault.centos.org/7.9.2009/os/x86_64/Packages/libpng-1.5.13-8.el7.x86_64.rpm
    sha256: e38e68875557c79dab8eea9aedaeea75787a2d1a88de118ecb0315c1833a1def
    target_directory: binary
  # - url: https://vault.centos.org/7.9.2009/os/Source/SPackages/libpng-1.5.13-8.el7.src.rpm
  #   target_directory: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: distro != "centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - '*'

requirements:
  build:
    - libarchive
  host:
    - sysroot_linux-64 2.17.*
  run:
    - sysroot_linux-64 2.17.*

tests:
  - script:
      - echo "it installs!"

about:
  homepage: http://www.libpng.org/pub/png/
  license: Zlib
  license_file: libpng-license
  summary: (CDT) A library of functions for manipulating PNG image format files
  description: |
    The libpng package contains a library of functions for creating and
    manipulating PNG (Portable Network Graphics) image format files.  PNG is a
    bit-mapped graphics format similar to the GIF format.  PNG was created to
    replace the GIF format, since GIF uses a patented data compression algorithm.
    Libpng should be installed if you need to manipulate PNG format image files.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
