schema_version: 1

# TODO: hack to workaround https://github.com/conda-forge/rattler-build-conda-compat/issues/112
context:
  cdt_build_number: 111
  distro: centos7

package:
  name: harfbuzz-conda-ppc64le
  version: 1.7.5

source:
  - url: https://vault.centos.org/altarch/7.9.2009/os/ppc64le/Packages/harfbuzz-1.7.5-2.el7.ppc64le.rpm
    sha256: c8adb94957c9310a524ec93c6ee04cd42630cfcb3b961d25095b87838dcbfd68
    target_directory: binary
  # - url: https://vault.centos.org/altarch/7.9.2009/os/Source/SPackages/harfbuzz-1.7.5-2.el7.src.rpm
  #   target_directory: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: distro != "centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - "*"

requirements:
  build:
    - libarchive
  host:
    - sysroot_linux-ppc64le 2.17.*
  run:
    - sysroot_linux-ppc64le 2.17.*

tests:
  - script:
      - echo "it installs!"

about:
  homepage: http://freedesktop.org/wiki/Software/HarfBuzz
  license: MIT
  license_file: binary/usr/share/licenses/harfbuzz-1.7.5/COPYING
  summary: (CDT) Text shaping library
  description: |
        HarfBuzz is an implementation of the OpenType Layout engine.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
