schema_version: 1

# TODO: hack to workaround https://github.com/conda-forge/rattler-build-conda-compat/issues/112
context:
  cdt_build_number: 111
  distro: centos7

package:
  name: libnl3-cli-conda-x86_64
  version: 3.2.28

source:
  - url: https://vault.centos.org/7.9.2009/os/x86_64/Packages/libnl3-cli-3.2.28-4.el7.x86_64.rpm
    sha256: 5b34fe927a1e7910594702be8d3def96dabbac6416f0ad42a2a2f4fcdbc9b22a
    target_directory: binary
  # - url: https://vault.centos.org/7.9.2009/os/Source/SPackages/libnl3-3.2.28-4.el7.src.rpm
  #   target_directory: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: distro != "centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - "*"

requirements:
  build:
    - libnl3-conda-x86_64 ==3.2.28 *_${{ cdt_build_number|int + 1000 }}
    - libarchive
  host:
    - libnl3-conda-x86_64 ==3.2.28 *_${{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.17.*
  run:
    - libnl3-conda-x86_64 ==3.2.28 *_${{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.17.*

tests:
  - script:
      - echo "it installs!"

about:
  homepage: http://www.infradead.org/~tgr/libnl/
  license: LGPL-2.0-only
  license_file: binary/usr/share/doc/libnl3-cli-3.2.28/COPYING
  summary: (CDT) Command line interface utils for libnl3
  description: |
        This package contains various libnl3 utils and additional libraries on which
        they depend

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
