schema_version: 1

# TODO: hack to workaround https://github.com/conda-forge/rattler-build-conda-compat/issues/112
context:
  cdt_build_number: 111
  distro: centos7

package:
  name: p11-kit-conda-aarch64
  version: 0.23.5

source:
  - url: https://vault.centos.org/altarch/7.9.2009/os/aarch64/Packages/p11-kit-0.23.5-3.el7.aarch64.rpm
    sha256: eb5bd186fe148b1d86a6cabe462fa0abe70d2856dcb21e25b74ff8597420a585
    target_directory: binary
  # - url: https://vault.centos.org/altarch/7.9.2009/os/Source/SPackages/p11-kit-0.23.5-3.el7.src.rpm
  #   target_directory: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: distro != "centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - '*'

requirements:
  build:
    - libarchive
  host:
    - sysroot_linux-aarch64 2.17.*
  run:
    - sysroot_linux-aarch64 2.17.*

tests:
  - script:
      - echo "it installs!"

about:
  homepage: http://p11-glue.freedesktop.org/p11-kit.html
  license: LicenseRef-Callaway-BSD
  license_file: p11-kit-license
  summary: (CDT) Library for loading and sharing PKCS#11 modules
  description: |
    p11-kit provides a way to load and enumerate PKCS#11 modules, as well as a
    standard configuration setup for installing PKCS#11 modules in such a way that
    they're discoverable.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
