schema_version: 1

package:
  name: libxxf86vm-devel-conda-x86_64
  version: 1.1.4

source:
  - url: https://vault.centos.org/7.9.2009/os/x86_64/Packages/libXxf86vm-devel-1.1.4-1.el7.x86_64.rpm
    sha256: 691bf47ba421d0d8782789cc5efc5fb0762c9e1193901dfe698ea7e5b1ed41e9
    target_directory: binary
    no_hoist: true
  # - url: https://vault.centos.org/7.9.2009/os/Source/SPackages/libXxf86vm-1.1.4-1.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: "distro != "\centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - "*"

requirements:
  build:
    - libxxf86vm-conda-x86_64 ==1.1.4 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libxxf86vm-conda-x86_64 ==1.1.4 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.17.*
  run:
    - libxxf86vm-conda-x86_64 ==1.1.4 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.17.*

tests:
  script:
    - "echo "it installs!""

about:
  license: MIT
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: (CDT) X.Org X11 libXxf86vm development package
  description: |
        X.Org X11 libXxf86vm development package


  homepage: http://www.x.org

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
