schema_version: 1

# TODO: hack to workaround https://github.com/conda-forge/rattler-build-conda-compat/issues/112
context:
  cdt_build_number: 111
  distro: centos7

package:
  name: libice-devel-conda-ppc64le
  version: 1.0.9

source:
  - url: https://vault.centos.org/altarch/7.9.2009/os/ppc64le/Packages/libICE-devel-1.0.9-9.el7.ppc64le.rpm
    sha256: 6e623317f8ca06df5724db8d1cc7f18a95f695cdd9a5d12e4861e002e8411ee6
    target_directory: binary
  # - url: https://vault.centos.org/altarch/7.9.2009/os/Source/SPackages/libICE-1.0.9-9.el7.src.rpm
  #   target_directory: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: distro != "centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - '*'

requirements:
  build:
    - libice-conda-ppc64le ==1.0.9 *_${{ cdt_build_number|int + 1000 }}
    - libarchive
  host:
    - libice-conda-ppc64le ==1.0.9 *_${{ cdt_build_number|int + 1000 }}
    - sysroot_linux-ppc64le 2.17.*
  run:
    - libice-conda-ppc64le ==1.0.9 *_${{ cdt_build_number|int + 1000 }}
    - sysroot_linux-ppc64le 2.17.*

tests:
  - script:
      - echo "it installs!"

about:
  homepage: http://www.x.org
  license: MIT
  license_file: libice-license
  summary: (CDT) X.Org X11 ICE development package
  description: |
    The X.Org X11 ICE (Inter-Client Exchange) development package.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
