schema_version: 1

# TODO: hack to workaround https://github.com/conda-forge/rattler-build-conda-compat/issues/112
context:
  cdt_build_number: 111
  distro: centos7

package:
  name: xorg-x11-server-common-conda-ppc64le
  version: 1.20.4

source:
  - url: https://vault.centos.org/altarch/7.9.2009/os/ppc64le/Packages/xorg-x11-server-common-1.20.4-10.el7.ppc64le.rpm
    sha256: 63b3ba24007c999e69d06ac013f5e4357b3e8e213b4f40b69c428993bee7eca6
    target_directory: binary
  # - url: https://vault.centos.org/altarch/7.9.2009/os/Source/SPackages/xorg-x11-server-1.20.4-10.el7.src.rpm
  #   target_directory: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: distro != "centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - '*'

requirements:
  build:
    - pixman-conda-ppc64le >=0.30.0 *_${{ cdt_build_number|int + 1000 }}
    - libarchive
  host:
    - pixman-conda-ppc64le >=0.30.0 *_${{ cdt_build_number|int + 1000 }}
    - sysroot_linux-ppc64le 2.17.*
  run:
    - pixman-conda-ppc64le >=0.30.0 *_${{ cdt_build_number|int + 1000 }}
    - sysroot_linux-ppc64le 2.17.*

tests:
  - script:
      - echo "it installs!"

about:
  homepage: http://www.x.org
  license: MIT
  license_file: x11-license
  summary: (CDT) Xorg server common files
  description: |
    Common files shared among all X servers.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
