schema_version: 1

package:
  name: numactl-libs-conda-x86_64
  version: 2.0.12

source:
  - url: https://vault.centos.org/7.9.2009/os/x86_64/Packages/numactl-libs-2.0.12-5.el7.x86_64.rpm
    sha256: cadd7d4125ce7b69bb020dc419c87600d4bd6d3ada1eed65c1472fb535b6b770
    target_directory: binary
    no_hoist: true
  # - url: https://vault.centos.org/7.9.2009/os/Source/SPackages/numactl-2.0.12-5.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: "distro != "\centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - "*"

requirements:
  host:
    - sysroot_linux-64 2.17.*
  run:
    - sysroot_linux-64 2.17.*

tests:
  script:
    - "echo "it installs!""

about:
  license: LGPLv2 and GPLv2
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: (CDT) libnuma libraries
  description: |
        numactl-libs provides libnuma, a library to do allocations with NUMA policy in
        applications.


  homepage: https://github.com/numactl/numactl

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
