schema_version: 1

# TODO: hack to workaround https://github.com/conda-forge/rattler-build-conda-compat/issues/112
context:
  cdt_build_number: 111
  distro: centos7

package:
  name: libglvnd-devel-conda-aarch64
  version: 1.0.1

source:
  - url: https://vault.centos.org/altarch/7.9.2009/os/aarch64/Packages/libglvnd-devel-1.0.1-0.8.git5baa1e5.el7.aarch64.rpm
    sha256: dd1889e284cf590cebbf3bf10d04c56dbc8abcfde7382de425164ae7a85a7ba3
    target_directory: binary
  # - url: https://vault.centos.org/altarch/7.9.2009/os/Source/SPackages/libglvnd-1.0.1-0.8.git5baa1e5.el7.src.rpm
  #   target_directory: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: distro != "centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - '*'

requirements:
  build:
    - libglvnd-conda-aarch64 ==1.0.1 *_${{ cdt_build_number|int + 1000 }}
    - libglvnd-core-devel-conda-aarch64 ==1.0.1 *_${{ cdt_build_number|int + 1000 }}
    - libglvnd-egl-conda-aarch64 ==1.0.1 *_${{ cdt_build_number|int + 1000 }}
    - libglvnd-gles-conda-aarch64 ==1.0.1 *_${{ cdt_build_number|int + 1000 }}
    - libglvnd-glx-conda-aarch64 ==1.0.1 *_${{ cdt_build_number|int + 1000 }}
    - libglvnd-opengl-conda-aarch64 ==1.0.1 *_${{ cdt_build_number|int + 1000 }}
    - libarchive
  host:
    - libglvnd-conda-aarch64 ==1.0.1 *_${{ cdt_build_number|int + 1000 }}
    - libglvnd-core-devel-conda-aarch64 ==1.0.1 *_${{ cdt_build_number|int + 1000 }}
    - libglvnd-egl-conda-aarch64 ==1.0.1 *_${{ cdt_build_number|int + 1000 }}
    - libglvnd-gles-conda-aarch64 ==1.0.1 *_${{ cdt_build_number|int + 1000 }}
    - libglvnd-glx-conda-aarch64 ==1.0.1 *_${{ cdt_build_number|int + 1000 }}
    - libglvnd-opengl-conda-aarch64 ==1.0.1 *_${{ cdt_build_number|int + 1000 }}
    - sysroot_linux-aarch64 2.17.*
  run:
    - libglvnd-conda-aarch64 ==1.0.1 *_${{ cdt_build_number|int + 1000 }}
    - libglvnd-core-devel-conda-aarch64 ==1.0.1 *_${{ cdt_build_number|int + 1000 }}
    - libglvnd-egl-conda-aarch64 ==1.0.1 *_${{ cdt_build_number|int + 1000 }}
    - libglvnd-gles-conda-aarch64 ==1.0.1 *_${{ cdt_build_number|int + 1000 }}
    - libglvnd-glx-conda-aarch64 ==1.0.1 *_${{ cdt_build_number|int + 1000 }}
    - libglvnd-opengl-conda-aarch64 ==1.0.1 *_${{ cdt_build_number|int + 1000 }}
    - sysroot_linux-aarch64 2.17.*
tests:
  - script:
      - echo "it installs!"

about:
  homepage: https://github.com/NVIDIA/libglvnd
  license: MIT
  license_file: libglvnd-license
  summary: (CDT) Development files for libglvnd
  description: |
    The libglvnd-devel package contains libraries and header files for developing
    applications that use libglvnd.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
