schema_version: 1

package:
  name: gtkmm24-devel-conda-x86_64
  version: 2.24.5

source:
  - url: https://vault.centos.org/7.9.2009/os/x86_64/Packages/gtkmm24-devel-2.24.5-1.el7.x86_64.rpm
    sha256: 394b1453366d738dce8c31ffe519b9e82d70dd798acb08f3aeed89852fe5cc67
    target_directory: binary
    no_hoist: true
  # - url: https://vault.centos.org/7.9.2009/os/Source/SPackages/gtkmm24-2.24.5-1.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: "distro != "\centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - "*"

requirements:
  build:
    - gtkmm24-conda-x86_64 ==2.24.5 *_{{ cdt_build_number|int + 1000 }}
  host:
    - gtkmm24-conda-x86_64 ==2.24.5 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.17.*
  run:
    - gtkmm24-conda-x86_64 ==2.24.5 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.17.*

tests:
  script:
    - "echo "it installs!""

about:
  license: LGPL-2.0-or-later
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: (CDT) Headers for developing programs that will use gtkmm24.
  description: |
        This package contains the static libraries and header files needed for
        developing gtkmm applications.


  homepage: http://www.gtkmm.org/

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
