schema_version: 1

package:
  name: libbonobo-conda-x86_64
  version: 2.32.1

source:
  - url: https://vault.centos.org/7.9.2009/os/x86_64/Packages/libbonobo-2.32.1-7.el7.x86_64.rpm
    sha256: 28cfaf8a6317893859922f2cc6f88af1ccb8dcdc7b789782fa3c9a7c36b09099
    target_directory: binary
    no_hoist: true
  # - url: https://vault.centos.org/7.9.2009/os/Source/SPackages/libbonobo-2.32.1-7.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: "distro != "\centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - "*"

requirements:
  host:
    - sysroot_linux-64 2.17.*
  run:
    - sysroot_linux-64 2.17.*

tests:
  script:
    - "echo "it installs!""

about:
  license: GPLv2+ and LGPLv2+
  license_file: {{ SRC_DIR }}/binary/usr/share/doc/libbonobo-2.32.1/COPYING
  summary: (CDT) Bonobo component system
  description: |
        Bonobo is a component system based on CORBA, used by the GNOME desktop.


  homepage: http://ftp.gnome.org

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
