schema_version: 1

package:
  name: ca-certificates-conda-aarch64
  version: 2020.2.41

source:
  - url: https://vault.centos.org/altarch/7.9.2009/os/aarch64/Packages/ca-certificates-2020.2.41-70.0.el7_8.noarch.rpm
    sha256: 1095e8edd8713c148159831eda79522d8eae5c52f1930b7a570a157f3ccf2fc2
    target_directory: binary
    no_hoist: true
  # - url: https://vault.centos.org/altarch/7.9.2009/os/Source/SPackages/ca-certificates-2020.2.41-70.0.el7_8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: "distro != "\centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - "*"

requirements:
  build:
    - p11-kit-conda-aarch64 >=0.23.5 *_{{ cdt_build_number|int + 1000 }}
    - p11-kit-trust-conda-aarch64 >=0.23.5 *_{{ cdt_build_number|int + 1000 }}
  host:
    - p11-kit-conda-aarch64 >=0.23.5 *_{{ cdt_build_number|int + 1000 }}
    - p11-kit-trust-conda-aarch64 >=0.23.5 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-aarch64 2.17.*
  run:
    - p11-kit-conda-aarch64 >=0.23.5 *_{{ cdt_build_number|int + 1000 }}
    - p11-kit-trust-conda-aarch64 >=0.23.5 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-aarch64 2.17.*

tests:
  script:
    - "echo "it installs!""

about:
  license: Public-Domain
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: (CDT) The Mozilla CA root certificate bundle
  description: |
        This package contains the set of CA certificates chosen by the Mozilla
        Foundation for use with the Internet PKI.


  homepage: http://www.mozilla.org/

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
