schema_version: 1

package:
  name: xcb-util-renderutil-conda-ppc64le
  version: 0.3.9

source:
  - url: https://vault.centos.org/altarch/7.9.2009/os/ppc64le/Packages/xcb-util-renderutil-0.3.9-3.el7.ppc64le.rpm
    sha256: 10dadc592a16472290207ec44781c6e652f8db4f4da3772792fbf6976b46216e
    target_directory: binary
    no_hoist: true
  # - url: https://vault.centos.org/altarch/7.9.2009/os/Source/SPackages/xcb-util-renderutil-0.3.9-3.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: "distro != "\centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - "*"

requirements:
  host:
    - sysroot_linux-ppc64le 2.17.*
  run:
    - sysroot_linux-ppc64le 2.17.*

tests:
  script:
    - "echo "it installs!""

about:
  license: MIT
  license_file: {{ SRC_DIR }}/binary/usr/share/doc/xcb-util-renderutil-0.3.9/COPYING
  summary: (CDT) Convenience functions for the Render extension
  description: |
        XCB util-renderutil module provides the following library:    - renderutil:
        Convenience functions for the Render extension.


  homepage: http://xcb.freedesktop.org

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
