schema_version: 1

package:
  name: libxi-conda-x86_64
  version: 1.7.9

source:
  - url: https://vault.centos.org/7.9.2009/os/x86_64/Packages/libXi-1.7.9-1.el7.x86_64.rpm
    sha256: 7ef78114fabd31ab69aaf5635b3845e10598b3c172759dc65b135f7cef624342
    target_directory: binary
    no_hoist: true
  # - url: https://vault.centos.org/7.9.2009/os/Source/SPackages/libXi-1.7.9-1.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: "distro != "\centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - "*"

requirements:
  build:
    - libx11-conda-x86_64 >=1.5.99.902 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libx11-conda-x86_64 >=1.5.99.902 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.17.*
  run:
    - libx11-conda-x86_64 >=1.5.99.902 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.17.*

tests:
  script:
    - "echo "it installs!""

about:
  license: MIT
  license_file: {{ SRC_DIR }}/binary/usr/share/doc/libXi-1.7.9/COPYING
  summary: (CDT) X.Org X11 libXi runtime library
  description: |
        X.Org X11 libXi runtime library


  homepage: http://www.x.org

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
