schema_version: 1

package:
  name: p11-kit-trust-conda-ppc64le
  version: 0.23.5

source:
  - url: https://vault.centos.org/altarch/7.9.2009/os/ppc64le/Packages/p11-kit-trust-0.23.5-3.el7.ppc64le.rpm
    sha256: adb8946ce2ea998ff24a67f73435461e58417789a8054e1a7e7ec7b635b35e87
    target_directory: binary
    no_hoist: true
  # - url: https://vault.centos.org/altarch/7.9.2009/os/Source/SPackages/p11-kit-0.23.5-3.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: "distro != "\centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - "*"

requirements:
  build:
    - p11-kit-conda-ppc64le ==0.23.5 *_{{ cdt_build_number|int + 1000 }}
  host:
    - p11-kit-conda-ppc64le ==0.23.5 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-ppc64le 2.17.*
  run:
    - p11-kit-conda-ppc64le ==0.23.5 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-ppc64le 2.17.*

tests:
  script:
    - "echo "it installs!""

about:
  license: BSD
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: (CDT) System trust module from p11-kit
  description: |
        The p11-kit-trust package contains a system trust PKCS#11 module which
        contains certificate anchors and black lists.


  homepage: http://p11-glue.freedesktop.org/p11-kit.html

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
