schema_version: 1

# TODO: hack to workaround https://github.com/conda-forge/rattler-build-conda-compat/issues/112
context:
  cdt_build_number: 111
  distro: centos7

package:
  name: cracklib-conda-ppc64le
  version: 2.9.0

source:
  - url: https://vault.centos.org/altarch/7.9.2009/os/ppc64le/Packages/cracklib-2.9.0-11.el7.ppc64le.rpm
    sha256: 4d10872c9b9cb81b495349256791192eb843fc49feb9be66cb5a6c6c76b88428
    target_directory: binary
  # - url: https://vault.centos.org/altarch/7.9.2009/os/Source/SPackages/cracklib-2.9.0-11.el7.src.rpm
  #   target_directory: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: distro != "centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - '*'

requirements:
  build:
    - libarchive
  host:
    - sysroot_linux-ppc64le 2.17.*
  run:
    - sysroot_linux-ppc64le 2.17.*

tests:
  - script:
      - echo "it installs!"

about:
  homepage: http://sourceforge.net/projects/cracklib/
  license: LGPL-2.0-or-later
  license_file: cracklib-copying.lib
  summary: (CDT) A password-checking library
  description: |
    CrackLib tests passwords to determine whether they match certain security-
    oriented characteristics, with the purpose of stopping users from choosing
    passwords that are easy to guess. CrackLib performs several tests on
    passwords: it tries to generate words from a username and gecos entry and
    checks those words against the password; it checks for simplistic patterns in
    passwords; and it checks for the password in a dictionary.  CrackLib is
    actually a library containing a particular C function which is used to check
    the password, as well as other C functions. CrackLib is not a replacement for
    a passwd program; it must be used in conjunction with an existing passwd
    program.  Install the cracklib package if you need a program to check users'
    passwords to see if they are at least minimally secure. If you install
    CrackLib, you will also want to install the cracklib-dicts package.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
