schema_version: 1

package:
  name: libsepol-devel-conda-ppc64le
  version: 2.5

source:
  - url: https://vault.centos.org/altarch/7.9.2009/os/ppc64le/Packages/libsepol-devel-2.5-10.el7.ppc64le.rpm
    sha256: f93d653d716719b2bb5952b55ab5f9295d8ec046867ffcb0ec30ebe5870d1b08
    target_directory: binary
    no_hoist: true
  # - url: https://vault.centos.org/altarch/7.9.2009/os/Source/SPackages/libsepol-2.5-10.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: "distro != "\centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - "*"

requirements:
  build:
    - libsepol-conda-ppc64le ==2.5 *_{{ cdt_build_number|int + 1000 }}
  host:
    - libsepol-conda-ppc64le ==2.5 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-ppc64le 2.17.*
  run:
    - libsepol-conda-ppc64le ==2.5 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-ppc64le 2.17.*

tests:
  script:
    - "echo "it installs!""

about:
  license: LGPL-2.0-or-later
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: (CDT) Header files and libraries used to build policy manipulation tools
  description: |
        The libsepol-devel package contains the libraries and header files needed for
        developing applications that manipulate binary policies.


  homepage: https://github.com/SELinuxProject/selinux/wiki

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
