schema_version: 1

# TODO: hack to workaround https://github.com/conda-forge/rattler-build-conda-compat/issues/112
context:
  cdt_build_number: 111
  distro: centos7

package:
  name: libpng-devel-conda-aarch64
  version: 1.5.13

source:
  - url: https://vault.centos.org/altarch/7.9.2009/os/aarch64/Packages/libpng-devel-1.5.13-8.el7.aarch64.rpm
    sha256: d958e50bb701a30ac8d4529722a2b7b70c472fc4e41e581feb277a8c94654d9c
    target_directory: binary
  # - url: https://vault.centos.org/altarch/7.9.2009/os/Source/SPackages/libpng-1.5.13-8.el7.src.rpm
  #   target_directory: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: distro != "centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - '*'

requirements:
  build:
    - libpng-conda-aarch64 ==1.5.13 *_${{ cdt_build_number|int + 1000 }}
    - libarchive
  host:
    - libpng-conda-aarch64 ==1.5.13 *_${{ cdt_build_number|int + 1000 }}
    - sysroot_linux-aarch64 2.17.*
  run:
    - libpng-conda-aarch64 ==1.5.13 *_${{ cdt_build_number|int + 1000 }}
    - sysroot_linux-aarch64 2.17.*

tests:
  - script:
      - echo "it installs!"

about:
  homepage: http://www.libpng.org/pub/png/
  license: Zlib
  license_file: libpng-license
  summary: (CDT) Development tools for programs to manipulate PNG image format files
  description: |
    The libpng-devel package contains header files and documentation necessary for
    developing programs using the PNG (Portable Network Graphics) library.  If you
    want to develop programs which will manipulate PNG image format files, you
    should install libpng-devel.  You'll also need to install the libpng package.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
