schema_version: 1

package:
  name: glib2-conda-aarch64
  version: 2.56.1

source:
  - url: https://vault.centos.org/altarch/7.9.2009/os/aarch64/Packages/glib2-2.56.1-7.el7.aarch64.rpm
    sha256: 53a22f871fee1b824c7a399c5cc90653cabd66812f0aa53c68348b2f06625276
    target_directory: binary
    no_hoist: true
  # - url: https://vault.centos.org/altarch/7.9.2009/os/Source/SPackages/glib2-2.56.1-7.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: "distro != "\centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - "*"

requirements:
  host:
    - sysroot_linux-aarch64 2.17.*
  run:
    - sysroot_linux-aarch64 2.17.*

tests:
  script:
    - "echo "it installs!""

about:
  license: LGPL-2.0-or-later
  license_file: {{ SRC_DIR }}/binary/usr/share/licenses/glib2-2.56.1/COPYING
  summary: (CDT) A library of handy utility functions
  description: |
        GLib is the low-level core library that forms the basis for projects such as
        GTK+ and GNOME. It provides data structure handling for C, portability
        wrappers, and interfaces for such runtime functionality as an event loop,
        threads, dynamic loading, and an object system.


  homepage: http://www.gtk.org

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
