schema_version: 1

package:
  name: xcb-util-conda-x86_64
  version: 0.4.0

source:
  - url: https://vault.centos.org/7.9.2009/os/x86_64/Packages/xcb-util-0.4.0-2.el7.x86_64.rpm
    sha256: 5e3365c77d8f0fa6d7f8bd42e100f885d0f75aa6177909ef8bb3db6d9701c7de
    target_directory: binary
    no_hoist: true
  # - url: https://vault.centos.org/7.9.2009/os/Source/SPackages/xcb-util-0.4.0-2.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: "distro != "\centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - "*"

requirements:
  host:
    - sysroot_linux-64 2.17.*
  run:
    - sysroot_linux-64 2.17.*

tests:
  script:
    - "echo "it installs!""

about:
  license: MIT
  license_file: {{ SRC_DIR }}/binary/usr/share/doc/xcb-util-0.4.0/COPYING
  summary: (CDT) Convenience libraries sitting on top of libxcb
  description: |
        The xcb-util module provides a number of libraries which sit on top of libxcb,
        the core X protocol library, and some of the extension libraries. These
        experimental libraries provide convenience functions and interfaces which make
        the raw X protocol more usable. Some of the libraries also provide client-side
        code which is not strictly part of the X protocol but which have traditionally
        been provided by Xlib.


  homepage: http://xcb.freedesktop.org

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
