schema_version: 1

# TODO: hack to workaround https://github.com/conda-forge/rattler-build-conda-compat/issues/112
context:
  cdt_build_number: 111
  distro: alma9

package:
  name: libsepol-devel-conda-x86_64
  version: 3.6

source:
  - url: https://repo.almalinux.org/almalinux/9.7/AppStream/x86_64/os/Packages/libsepol-devel-3.6-3.el9.x86_64.rpm
    sha256: e3df760b7db6ceb7c770524b5635723c73f3c9f669a96bde5db4c3b5d97bfb33
    target_directory: binary
  # - url: https://repo.almalinux.org/almalinux/9.7/AppStream/Source/Packages/libsepol-3.6-3.el9.src.rpm
  #   target_directory: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: distro != "alma9"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - '*'

requirements:
  build:
    - libsepol-conda-x86_64 ==3.6 *_${{ cdt_build_number|int + 1000 }}
    - libarchive
  host:
    - libsepol-conda-x86_64 ==3.6 *_${{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.34.*
  run:
    - libsepol-conda-x86_64 ==3.6 *_${{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.34.*

tests:
  - script:
      - echo "it installs!"

about:
  homepage: https://github.com/SELinuxProject/selinux/wiki
  license: LGPL-2.0-or-later
  license_file: libsepol-license
  summary: (CDT) Header files and libraries used to build policy manipulation tools
  description: |
    The libsepol-devel package contains the libraries and header files needed for
    developing applications that manipulate binary policies.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
