schema_version: 1

package:
  name: opensm-libs-conda-aarch64
  version: 3.3.21

source:
  - url: https://vault.centos.org/altarch/7.9.2009/os/aarch64/Packages/opensm-libs-3.3.21-3.el7_8.aarch64.rpm
    sha256: e632beaafcaa0d3e3d35647fd30311ce84177f5d2714b91b2321014e102a0b55
    target_directory: binary
    no_hoist: true
  # - url: https://vault.centos.org/altarch/7.9.2009/os/Source/SPackages/opensm-3.3.21-3.el7_8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: "distro != "\centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - "*"

requirements:
  host:
    - sysroot_linux-aarch64 2.17.*
  run:
    - sysroot_linux-aarch64 2.17.*

tests:
  script:
    - "echo "it installs!""

about:
  license: GPLv2 or BSD
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: (CDT) Libraries used by opensm and included utilities
  description: |
        Shared libraries for Infiniband user space access


  homepage: https://github.com/linux-rdma/opensm

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
