schema_version: 1

package:
  name: cracklib-devel-conda-aarch64
  version: 2.9.6

source:
  - url: https://repo.almalinux.org/almalinux/8.10/PowerTools/aarch64/os/Packages/cracklib-devel-2.9.6-15.el8.aarch64.rpm
    sha256: 4c99def23773c7bd29501052e7e9c3168c2d2cf475020158d03f3c2cd1a8b370
    target_directory: binary
    no_hoist: true
  # - url: https://repo.almalinux.org/almalinux/8.10/PowerTools/Source/Packages/cracklib-2.9.6-15.el8.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: "distro != "\alma8"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - "*"

requirements:
  build:
    - cracklib-conda-aarch64 ==2.9.6 *_{{ cdt_build_number|int + 1000 }}
  host:
    - cracklib-conda-aarch64 ==2.9.6 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-aarch64 2.28.*
  run:
    - cracklib-conda-aarch64 ==2.9.6 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-aarch64 2.28.*

tests:
  script:
    - "echo "it installs!""

about:
  license: LGPL-2.0-or-later
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: (CDT) Development files needed for building applications which use cracklib
  description: |
        The cracklib-devel package contains the header files and libraries needed for
        compiling applications which use cracklib.


  homepage: http://sourceforge.net/projects/cracklib/

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
