schema_version: 1

package:
  name: libibumad-conda-aarch64
  version: 22.4

source:
  - url: https://vault.centos.org/altarch/7.9.2009/os/aarch64/Packages/libibumad-22.4-5.el7.aarch64.rpm
    sha256: f3eb9031498d050772cdb7a879c88effa27124dd5704f23d99cb196e4800f109
    target_directory: binary
    no_hoist: true
  # - url: https://vault.centos.org/altarch/7.9.2009/os/Source/SPackages/rdma-core-22.4-5.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: "distro != "\centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - "*"

requirements:
  build:
    - rdma-core-conda-aarch64 ==22.4 *_{{ cdt_build_number|int + 1000 }}
  host:
    - rdma-core-conda-aarch64 ==22.4 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-aarch64 2.17.*
  run:
    - rdma-core-conda-aarch64 ==22.4 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-aarch64 2.17.*

tests:
  script:
    - "echo "it installs!""

about:
  license: GPLv2 or BSD
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: (CDT) OpenFabrics Alliance InfiniBand umad (userspace management datagram) library
  description: |
        libibumad provides the userspace management datagram (umad) library functions,
        which sit on top of the umad modules in the kernel. These are used by the IB
        diagnostic and management tools, including OpenSM.


  homepage: https://github.com/linux-rdma/rdma-core

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
