schema_version: 1

# TODO: hack to workaround https://github.com/conda-forge/rattler-build-conda-compat/issues/112
context:
  cdt_build_number: 111
  distro: alma8

package:
  name: libpwquality-devel-conda-aarch64
  version: 1.4.4

source:
  - url: https://repo.almalinux.org/almalinux/8.10/PowerTools/aarch64/os/Packages/libpwquality-devel-1.4.4-6.el8.aarch64.rpm
    sha256: 691721ee59cde205c73cff769666b4cc4e256d8d7605c03a0d1d4b362d1432c6
    target_directory: binary
  # - url: https://repo.almalinux.org/almalinux/8.10/PowerTools/Source/Packages/libpwquality-1.4.4-6.el8.src.rpm
  #   target_directory: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: distro != "alma8"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - '*'

requirements:
  build:
    - libpwquality-conda-aarch64 ==1.4.4 *_${{ cdt_build_number|int + 1000 }}
    - libarchive
  host:
    - libpwquality-conda-aarch64 ==1.4.4 *_${{ cdt_build_number|int + 1000 }}
    - sysroot_linux-aarch64 2.28.*
  run:
    - libpwquality-conda-aarch64 ==1.4.4 *_${{ cdt_build_number|int + 1000 }}
    - sysroot_linux-aarch64 2.28.*

tests:
  - script:
      - echo "it installs!"

about:
  homepage: https://github.com/libpwquality/libpwquality/
  license: LicenseRef-Callaway-BSD OR GPL-2.0-or-later
  license_file: libpwquality-copying
  summary: (CDT) Support for development of applications using the libpwquality library
  description: |
    Files needed for development of applications using the libpwquality library.
    See the pwquality.h header file for the API.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
