schema_version: 1

# TODO: hack to workaround https://github.com/conda-forge/rattler-build-conda-compat/issues/112
context:
  cdt_build_number: 111
  distro: alma9

package:
  name: audit-libs-conda-x86_64
  version: 3.1.5

source:
  - url: https://repo.almalinux.org/almalinux/9.7/BaseOS/x86_64/os/Packages/audit-libs-3.1.5-7.el9.x86_64.rpm
    sha256: 3550d2f54bc253a69bd5b467c3482299d5bfdc38cd798d014f7cb4ea7f6d400e
    target_directory: binary
  # - url: https://repo.almalinux.org/almalinux/9.7/BaseOS/Source/Packages/audit-3.1.5-7.el9.src.rpm
  #   target_directory: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: distro != "alma9"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - '*'

requirements:
  build:
    - libarchive
  host:
    - sysroot_linux-64 2.34.*
  run:
    - sysroot_linux-64 2.34.*

tests:
  - script:
      - echo "it installs!"

about:
  homepage: http://people.redhat.com/sgrubb/audit/
  license: LGPL-2.0-or-later
  license_file: audit-libs-copying.lib
  summary: (CDT) Dynamic library for libaudit
  description: |
    The audit-libs package contains the dynamic libraries needed for applications
    to use the audit framework.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
