schema_version: 1

package:
  name: libjpeg-turbo-conda-ppc64le
  version: 1.2.90

source:
  - url: https://vault.centos.org/altarch/7.9.2009/os/ppc64le/Packages/libjpeg-turbo-1.2.90-8.el7.ppc64le.rpm
    sha256: 17ffe084dbdb0af7a1399f460fbd8260caa691ddfdb125fc0f68886e05b1ae02
    target_directory: binary
    no_hoist: true
  # - url: https://vault.centos.org/altarch/7.9.2009/os/Source/SPackages/libjpeg-turbo-1.2.90-8.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: "distro != "\centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - "*"

requirements:
  host:
    - sysroot_linux-ppc64le 2.17.*
  run:
    - sysroot_linux-ppc64le 2.17.*

tests:
  script:
    - "echo "it installs!""

about:
  license: IJG
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: (CDT) A MMX/SSE2 accelerated library for manipulating JPEG image files
  description: |
        The libjpeg-turbo package contains a library of functions for manipulating
        JPEG images.


  homepage: http://sourceforge.net/projects/libjpeg-turbo

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
