schema_version: 1

# TODO: hack to workaround https://github.com/conda-forge/rattler-build-conda-compat/issues/112
context:
  cdt_build_number: 111
  distro: centos7

package:
  name: libbonobo-devel-conda-ppc64le
  version: 2.32.1

source:
  - url: https://vault.centos.org/altarch/7.9.2009/os/ppc64le/Packages/libbonobo-devel-2.32.1-7.el7.ppc64le.rpm
    sha256: 06ac1552ec51ba7fcf586ac79490c5ce1496901494bf4abc8d57eb877a38bd9f
    target_directory: binary
  # - url: https://vault.centos.org/altarch/7.9.2009/os/Source/SPackages/libbonobo-2.32.1-7.el7.src.rpm
  #   target_directory: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: distro != "centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - '*'

requirements:
  build:
    - orbit2-devel-conda-ppc64le >=2.7.5 *_${{ cdt_build_number|int + 1000 }}
    - libbonobo-conda-ppc64le ==2.32.1 *_${{ cdt_build_number|int + 1000 }}
    - libxml2-devel-conda-ppc64le >=2.4.21 *_${{ cdt_build_number|int + 1000 }}
    - libarchive
  host:
    - orbit2-devel-conda-ppc64le >=2.7.5 *_${{ cdt_build_number|int + 1000 }}
    - libbonobo-conda-ppc64le ==2.32.1 *_${{ cdt_build_number|int + 1000 }}
    - libxml2-devel-conda-ppc64le >=2.4.21 *_${{ cdt_build_number|int + 1000 }}
    - sysroot_linux-ppc64le 2.17.*
  run:
    - orbit2-devel-conda-ppc64le >=2.7.5 *_${{ cdt_build_number|int + 1000 }}
    - libbonobo-conda-ppc64le ==2.32.1 *_${{ cdt_build_number|int + 1000 }}
    - libxml2-devel-conda-ppc64le >=2.4.21 *_${{ cdt_build_number|int + 1000 }}
    - sysroot_linux-ppc64le 2.17.*

tests:
  - script:
      - echo "it installs!"

about:
  homepage: http://ftp.gnome.org
  license: GPL-2.0-or-later AND LGPL-2.0-or-later
  license_file:
    - libbonobo-copying
    - libbonobo-copying.lib
  summary: (CDT) Libraries and headers for libbonobo
  description: |
    Bonobo is a component system based on CORBA, used by the GNOME desktop.  This
    package contains header files used to compile programs that use Bonobo.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
