schema_version: 1

package:
  name: libidl-conda-ppc64le
  version: 0.8.14

source:
  - url: https://vault.centos.org/altarch/7.9.2009/os/ppc64le/Packages/libIDL-0.8.14-8.el7.ppc64le.rpm
    sha256: 0a3f9c0b68864a4ace641c0a9fa5d96b3365e47bc8566b5b1124c4c61b4dd86f
    target_directory: binary
    no_hoist: true
  # - url: https://vault.centos.org/altarch/7.9.2009/os/Source/SPackages/libIDL-0.8.14-8.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: "distro != "\centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - "*"

requirements:
  host:
    - sysroot_linux-ppc64le 2.17.*
  run:
    - sysroot_linux-ppc64le 2.17.*

tests:
  script:
    - "echo "it installs!""

about:
  license: LGPL-2.0-or-later
  license_file: {{ SRC_DIR }}/binary/usr/share/doc/libIDL-0.8.14/COPYING
  summary: (CDT) Library for parsing IDL (Interface Definition Language)
  description: |
        libIDL is a library for parsing IDL (Interface Definition Language). It can be
        used for both COM-style and CORBA-style IDL.


  homepage: http://ftp.gnome.org/pub/gnome/sources/libIDL/0.8/

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
