schema_version: 1

# TODO: hack to workaround https://github.com/conda-forge/rattler-build-conda-compat/issues/112
context:
  cdt_build_number: 111
  distro: centos7

package:
  name: orbit2-conda-ppc64le
  version: 2.14.19

source:
  - url: https://vault.centos.org/altarch/7.9.2009/os/ppc64le/Packages/ORBit2-2.14.19-13.el7.ppc64le.rpm
    sha256: f7c5df0eba268db12f528d0363bc0b61ff9637c2e92e178d3a0bf193a44a0485
    target_directory: binary
  # - url: https://vault.centos.org/altarch/7.9.2009/os/Source/SPackages/ORBit2-2.14.19-13.el7.src.rpm
  #   target_directory: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: distro != "centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - '*'

requirements:
  build:
    - libarchive
  host:
    - sysroot_linux-ppc64le 2.17.*
  run:
    - sysroot_linux-ppc64le 2.17.*

tests:
  - script:
      - echo "it installs!"

about:
  homepage: http://www.gnome.org/projects/ORBit2
  license: LGPL-2.0-or-later AND GPL-2.0-or-later
  license_file:
    - orbit2-copying
    - orbit2-copying.lib
  summary: (CDT) A high-performance CORBA Object Request Broker
  description: |
    ORBit is a high-performance CORBA (Common Object Request Broker Architecture)
    ORB (object request broker). It allows programs to send requests and receive
    replies from other programs, regardless of the locations of the two programs.
    CORBA is an architecture that enables communication between program objects,
    regardless of the programming language they're written in or the operating
    system they run on.  You will need to install this package and ORBit-devel if
    you want to write programs that use CORBA technology.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
