schema_version: 1

package:
  name: harfbuzz-conda-aarch64
  version: 1.7.5

source:
  - url: https://vault.centos.org/altarch/7.9.2009/os/aarch64/Packages/harfbuzz-1.7.5-2.el7.aarch64.rpm
    sha256: 8229d1e457c709a2a54cfd05b2682011d253d9060ac53c14c297355540bd225b
    target_directory: binary
    no_hoist: true
  # - url: https://vault.centos.org/altarch/7.9.2009/os/Source/SPackages/harfbuzz-1.7.5-2.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: "distro != "\centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - "*"

requirements:
  host:
    - sysroot_linux-aarch64 2.17.*
  run:
    - sysroot_linux-aarch64 2.17.*

tests:
  script:
    - "echo "it installs!""

about:
  license: MIT
  license_file: {{ SRC_DIR }}/binary/usr/share/licenses/harfbuzz-1.7.5/COPYING
  summary: (CDT) Text shaping library
  description: |
        HarfBuzz is an implementation of the OpenType Layout engine.


  homepage: http://freedesktop.org/wiki/Software/HarfBuzz

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
