schema_version: 1

package:
  name: gtk2-devel-conda-x86_64
  version: 2.24.31

source:
  - url: https://vault.centos.org/7.9.2009/os/x86_64/Packages/gtk2-devel-2.24.31-1.el7.x86_64.rpm
    sha256: 0d5303d89e65fa5a6231ed9740f1aa64621bfeff5bdfec01ccc3588c5bc74553
    target_directory: binary
    no_hoist: true
  # - url: https://vault.centos.org/7.9.2009/os/Source/SPackages/gtk2-2.24.31-1.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: "distro != "\centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - "*"

requirements:
  build:
    - atk-devel-conda-x86_64 >=1.29.4 *_{{ cdt_build_number|int + 1000 }}
    - cairo-devel-conda-x86_64 >=1.6.0 *_{{ cdt_build_number|int + 1000 }}
    - glib2-devel-conda-x86_64 >=2.28.0 *_{{ cdt_build_number|int + 1000 }}
    - gtk2-conda-x86_64 ==2.24.31 *_{{ cdt_build_number|int + 1000 }}
    - pango-devel-conda-x86_64 >=1.20.0 *_{{ cdt_build_number|int + 1000 }}
  host:
    - atk-devel-conda-x86_64 >=1.29.4 *_{{ cdt_build_number|int + 1000 }}
    - cairo-devel-conda-x86_64 >=1.6.0 *_{{ cdt_build_number|int + 1000 }}
    - glib2-devel-conda-x86_64 >=2.28.0 *_{{ cdt_build_number|int + 1000 }}
    - gtk2-conda-x86_64 ==2.24.31 *_{{ cdt_build_number|int + 1000 }}
    - pango-devel-conda-x86_64 >=1.20.0 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.17.*
  run:
    - atk-devel-conda-x86_64 >=1.29.4 *_{{ cdt_build_number|int + 1000 }}
    - cairo-devel-conda-x86_64 >=1.6.0 *_{{ cdt_build_number|int + 1000 }}
    - glib2-devel-conda-x86_64 >=2.28.0 *_{{ cdt_build_number|int + 1000 }}
    - gtk2-conda-x86_64 ==2.24.31 *_{{ cdt_build_number|int + 1000 }}
    - pango-devel-conda-x86_64 >=1.20.0 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-64 2.17.*

tests:
  script:
    - "echo "it installs!""

about:
  license: LGPL-2.0-or-later
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: (CDT) Development files for GTK+
  description: |
        This package contains the libraries and header files that are needed for
        writing applications with the GTK+ widget toolkit. If you plan to develop
        applications with GTK+, consider installing the gtk2-devel-docs package.


  homepage: http://www.gtk.org

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
