schema_version: 1

# TODO: hack to workaround https://github.com/conda-forge/rattler-build-conda-compat/issues/112
context:
  cdt_build_number: 111
  distro: centos7

package:
  name: kmod-libs-conda-aarch64
  version: 20

source:
  - url: https://vault.centos.org/altarch/7.9.2009/os/aarch64/Packages/kmod-libs-20-28.el7.aarch64.rpm
    sha256: 0b101c5500ec346a4e904a5e791e526f7027bd13187af6f6604b4ff6d3178d6b
    target_directory: binary
  # - url: https://vault.centos.org/altarch/7.9.2009/os/Source/SPackages/kmod-20-28.el7.src.rpm
  #   target_directory: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: distro != "centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - '*'

requirements:
  build:
    - libarchive
  host:
    - sysroot_linux-aarch64 2.17.*
  run:
    - sysroot_linux-aarch64 2.17.*

tests:
  - script:
      - echo "it installs!"

about:
  homepage: http://git.kernel.org/?p=utils/kernel/kmod/kmod.git;a=summary
  license: LGPL-2.0-or-later
  license_file: kmod-copying
  summary: (CDT) Libraries to handle kernel module loading and unloading
  description: |
    The kmod-libs package provides runtime libraries for any application that
    wishes to load or unload Linux kernel modules from the running system.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
