schema_version: 1

package:
  name: at-spi-devel-conda-aarch64
  version: 1.32.0

source:
  - url: https://vault.centos.org/altarch/7.9.2009/os/aarch64/Packages/at-spi-devel-1.32.0-12.el7.aarch64.rpm
    sha256: 1e973bd5e679594b4eda8c665b99d86c5b468e152aac7673f9934c3207a98d65
    target_directory: binary
    no_hoist: true
  # - url: https://vault.centos.org/altarch/7.9.2009/os/Source/SPackages/at-spi-1.32.0-12.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  # this skip is here because we need different package hashes per distro.
  # we therefore list all possible values in CBC and skip those we don't want;
  # use in a selector ensures that the `distro` variable shows up in the hash
  number: ${{ cdt_build_number|int + 1000 }}
  skip: "distro != "\centos7"
  noarch: generic
  prefix_detection:
    ignore_binary_files: false
  dynamic_linking:
    binary_relocation: false
    missing_dso_allowlist:
      - "*"

requirements:
  build:
    - orbit2-devel-conda-aarch64 >=2.6.0 *_{{ cdt_build_number|int + 1000 }}
    - at-spi-conda-aarch64 ==1.32.0 *_{{ cdt_build_number|int + 1000 }}
    - atk-devel-conda-aarch64 >=1.29.2 *_{{ cdt_build_number|int + 1000 }}
    - gail-devel-conda-aarch64 >=2.24.31 *_{{ cdt_build_number|int + 1000 }}
    - gtk2-devel-conda-aarch64 >=2.10.0 *_{{ cdt_build_number|int + 1000 }}
    - libbonobo-devel-conda-aarch64 >=2.4.0 *_{{ cdt_build_number|int + 1000 }}
  host:
    - orbit2-devel-conda-aarch64 >=2.6.0 *_{{ cdt_build_number|int + 1000 }}
    - at-spi-conda-aarch64 ==1.32.0 *_{{ cdt_build_number|int + 1000 }}
    - atk-devel-conda-aarch64 >=1.29.2 *_{{ cdt_build_number|int + 1000 }}
    - gail-devel-conda-aarch64 >=2.24.31 *_{{ cdt_build_number|int + 1000 }}
    - gtk2-devel-conda-aarch64 >=2.10.0 *_{{ cdt_build_number|int + 1000 }}
    - libbonobo-devel-conda-aarch64 >=2.4.0 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-aarch64 2.17.*
  run:
    - orbit2-devel-conda-aarch64 >=2.6.0 *_{{ cdt_build_number|int + 1000 }}
    - at-spi-conda-aarch64 ==1.32.0 *_{{ cdt_build_number|int + 1000 }}
    - atk-devel-conda-aarch64 >=1.29.2 *_{{ cdt_build_number|int + 1000 }}
    - gail-devel-conda-aarch64 >=2.24.31 *_{{ cdt_build_number|int + 1000 }}
    - gtk2-devel-conda-aarch64 >=2.10.0 *_{{ cdt_build_number|int + 1000 }}
    - libbonobo-devel-conda-aarch64 >=2.4.0 *_{{ cdt_build_number|int + 1000 }}
    - sysroot_linux-aarch64 2.17.*

tests:
  script:
    - "echo "it installs!""

about:
  license: LGPL-2.0-or-later
  license_file: {{ SRC_DIR }}/binary/LICENSE_NOT_FOUND
  summary: (CDT) Development files for at-spi
  description: |
        This package contains libraries, header files and developer documentation
        needed for developing applications that interact directly with at-spi.


  homepage: http://developer.gnome.org/projects/gap/

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
